#!/bin/bash
source ./venv/bin/activate

get_submodules () {
  submodules=($(git submodule | awk '{ print $2 }'))
  submodules+=(".")
}

build_requirements_txt () {
  check_file="prod"
  write_file="server"
  if [[ "$1" = "local" ]]; then
    check_file="dev"
    write_file="local"

  fi

  touch dummy.requirements.in

  get_submodules

  for submodule in "${submodules[@]}"
  do
    file_name="$submodule/requirements/$check_file.requirements.in"
    if [ -f "$file_name" ]; then
          cat "$file_name" >> dummy.requirements.in
          printf "\n" >> dummy.requirements.in
    fi
  done


  pip-compile --output-file requirements/"$write_file".requirements.txt dummy.requirements.in

  rm -f dummy.requirements.in
}

if [ $# -eq 0 ]
  then
    echo "No arguments supplied please pass local or server"
  else
    possible_input=("local" "server")
    invalid_msg=true
    for value in "${possible_input[@]}"
    do
      [[ "$1" = "$value" ]] && build_requirements_txt "$1" && invalid_msg=false
    done
fi
