#!/bin/bash
# check value
if [ $# -eq 0 ]
  then
    echo "No arguments supplied please pass local or server"
  else
    possible_input=("local" "server")
    invalid_msg=true
    for value in "${possible_input[@]}"
    do
      [[ "$1" = "$value" ]] && invalid_msg=false
    done
fi

if [[ $invalid_msg = true ]]
then
  echo Possible values are "${possible_input[@]}" && exit
fi

source ./venv/bin/activate
pip install -r requirements/"$1".requirements.txt
